"servers":
  533368376148361216:
    "on_message":
      "roles":
        5:
          "id": 533369804334039061
        10:
          "id": 533369803965071381
        20:
          "id": 533369912207474706
        30:
          "id": 533369949591175169
        40:
          "id": 783765499246936064
        50:
          "id": 573702137918390272
        69:
          "id": 655885436656549898
        75:
          "id": 655885354401923132
        100:
          "id": 655885489324294184
      "pics_only":
        538110190902312976: "To keep #lets-draw clean, only posts with pictures are allowed. Discuss art in #lets-draw-discussion!"

    "on_member_update":
      - "role": 533499454964105245
        "channel": "general-chat"
        "message": "Welcome to the server, {mention}!\\n- Tag your interests and unlock different areas at [#choose-roles]\\n- Check out [#server-guide]\\n\\nIf you have any questions, feel free to message a moderator or post in [#help-and-advice]."
      
      - "role": 533369804334039061
        "channel": "general-chat"
        "message": "Congrats, {mention}! You unlocked the [#server-portal] and the Second Floor. Check out [#thoughtful-discussion], [#venting], and more! You can grab the NSFW role in [#choose-roles] to access the NSFW channels."
      
      - "role": 533369912207474706
          "channel": "general-chat"
          "message": "Congrats, {mention}! You unlocked the Test Lab. Check out [#signup] to become a server tester!"

      - "role": 655885436656549898
          "channel": "general-chat",
          "message": "{mention} Nice."

  662365002556243993:
    "on_message":
      "roles":
        5:
          "id": 668184294983991316
        8:
          "id": 662394541202079744