default:
  on_message:
    mee6_level_up:
      enabled: false
      message_pattern: <@(?:.+)>.+level ([0-9]+)
      bot_id: 292191677471260682

  inactivity:
    days_threshold: 14
    include_reactions: false
    message_enabled: true
    message_invite_enabled: false
    message_invite_hours: 24
    message_invite_max_uses: 1
    message_invite_reason: In case user returns from inactivity
    message: |-
      Hello, you've been marked as inactive on ***{server}***.
      
      (Do not reply here. This is an automated message and any replies will be ignored)

  commands:
    define:
      enabled: true
      visible: true
      description: Gives the definition of a term.
      usage: "[term]"
      cache_limit: 2000
      base_api_url: https://dictionaryapi.com/api/v3/references/collegiate/json/
      base_url: https://www.merriam-webster.com/dictionary/

    edit:
      enabled: true
      visible: true
      description: Edit a message sent through me.
      usage: "[#channel]"
      help: |-
        Paste the message ID when prompted, then enter the new message.

        To get the message ID, enable developer mode in Settings (Gear Icon) > Appearance > Advanced > Developer Mode.

        (PC) Hover to the right of the message and click the three vertical dots > Copy ID.
        (Mobile) Tap and hold the message > Copy ID.
      timeout_id_prompt: 300
      timeout_edit: 900

    exempt:
      enabled: false
      visible: false

    inactivelist:
      enabled: true
      visible: true
      aliases:
        - purgelist
      description: Shows a list of inactive members in the server.

    inactivenotify:
      enabled: true
      visible: true
      aliases:
        - purgenotify
      description: Notifies all inactivelist members about their inactivity.

    message:
      enabled: true
      visible: true
      description: Send a message through me.
      usage: "[#channel/@user] [message]"

    purgeleaderboard:
      enabled: true
      visible: true
      description: Get a list of members on the MEE6 leaderboard who are no longer on the server.

    shutdown:
      enabled: true
      visible: false
      description: Shut me down :c (Bot-owner only)
    
    test:
      enabled: true
      visible: false
      description: testing

    wordcloud:
      enabled: true
      visible: true
      description: Summarizes a server's, channel's, or user's message history into a word cloud.
      usage: "[#channel/@username] (optional)"

servers:
  533368376148361216:
    on_message:
      mee6_level_up:
        enabled: true
        roles:
          8000:
            id: 816919695340994561

    on_member_update:
      role_message:
        enabled: true
        roles:
          816919695340994561:
            name: test role
            channel: "mod-testing"
            message: |-
              Welcome to the server, {mention}!
              - Tag your interests and unlock different areas at [#choose-roles]
              - Check out [#server-guide]
              
              If you have any questions, feel free to message a moderator or post in [#help-and-advice].
    
    inactivity:
      days_threshold: 14
      include_reactions: true
      message_invite_enabled: true
      message_invite_hours: 168
      message_invite_channel: 533372732176334861
      message: |-
        Hello, you are about to be kicked for inactivity at ***{server}***. Don't worry though, you're welcome back anytime! You can use the invite below to rejoin the server. If the link expires, message `{owner_name}#{owner_discriminator}` for another invite back.
        
        (If you were exempt by a moderator, please ignore this message.)
