default:
  cmd_prefix: t;
  description: For humanity!
  status: Testing beepboop | {prefix}help

standards:
  embed:
    title_limit: 256
    description_limit: 2048
    field_limit: 25
    field_name_limit: 256
    field_value_limit: 1024
    footer_limit: 2048
    author_name_limit: 256
    total_character_limit: 6000

  message:
    content_limit: 2000
