---
version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: "[%(asctime)s][%(levelname)s: %(name)s] %(message)s"
    datefmt: "%b %d - %H:%M:%S"

  detailed:
    format: "[%(asctime)s][%(levelname)s: %(name)s - line %(lineno)d] %(message)s"
    datefmt: "%Y-%b-%d %H:%M:%S"

handlers:
  root:
    class: logging.handlers.RotatingFileHandler
    level: WARN
    maxBytes: 10485760 # 10MB
    filename: logs/root.log
    formatter: detailed

  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple

  debug_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    filename: logs/debug.log
    maxBytes: 10485760 # 10MB
    backupCount: 5
    formatter: detailed

  info_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    filename: logs/info.log
    maxBytes: 10485760 # 10MB
    formatter: simple

  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    filename: logs/error.log
    maxBytes: 10485760 # 10MB
    formatter: detailed

loggers:
  root:
    level: WARN
    handlers: [root]

  bot:
    level: DEBUG
    handlers: [debug_file, console, info_file, error_file]

  database:
    level: DEBUG
    handlers: [debug_file, error_file]
